version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      FTLCONF_webserver_port: '8080,8443os,[::]:8080,[::]:8443os'
    cap_add:
      - NET_ADMIN
